# Generated by Django 3.1.1 on 2020-09-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='st_totall_football',
            new_name='st_totall_footfall',
        ),
    ]
