# Generated by Django 3.1.1 on 2020-09-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200926_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='st_returns',
            new_name='st_returning_footfall',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='st_totall_footfall',
            new_name='st_total_footfall',
        ),
    ]
